// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/consumer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_proto_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *JoinGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinGroupRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type JoinGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	GenerationId  int32                  `protobuf:"varint,2,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	IsLeader      bool                   `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	Members       []string               `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	mi := &file_proto_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *JoinGroupResponse) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *JoinGroupResponse) GetGenerationId() int32 {
	if x != nil {
		return x.GenerationId
	}
	return 0
}

func (x *JoinGroupResponse) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *JoinGroupResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SyncGroupRequest struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	GroupId       string                          `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ConsumerId    string                          `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	GenerationId  int32                           `protobuf:"varint,3,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	Assignments   map[string]*PartitionAssignment `protobuf:"bytes,4,rep,name=assignments,proto3" json:"assignments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // consumer_id -> assignment (sent by leader only)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGroupRequest) Reset() {
	*x = SyncGroupRequest{}
	mi := &file_proto_consumer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGroupRequest) ProtoMessage() {}

func (x *SyncGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGroupRequest.ProtoReflect.Descriptor instead.
func (*SyncGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_proto_rawDescGZIP(), []int{2}
}

func (x *SyncGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SyncGroupRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *SyncGroupRequest) GetGenerationId() int32 {
	if x != nil {
		return x.GenerationId
	}
	return 0
}

func (x *SyncGroupRequest) GetAssignments() map[string]*PartitionAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type PartitionAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []int32                `protobuf:"varint,1,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionAssignment) Reset() {
	*x = PartitionAssignment{}
	mi := &file_proto_consumer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionAssignment) ProtoMessage() {}

func (x *PartitionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionAssignment.ProtoReflect.Descriptor instead.
func (*PartitionAssignment) Descriptor() ([]byte, []int) {
	return file_proto_consumer_proto_rawDescGZIP(), []int{3}
}

func (x *PartitionAssignment) GetPartitions() []int32 {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type SyncGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignment    *PartitionAssignment   `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGroupResponse) Reset() {
	*x = SyncGroupResponse{}
	mi := &file_proto_consumer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGroupResponse) ProtoMessage() {}

func (x *SyncGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGroupResponse.ProtoReflect.Descriptor instead.
func (*SyncGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_proto_rawDescGZIP(), []int{4}
}

func (x *SyncGroupResponse) GetAssignment() *PartitionAssignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	GenerationId  int32                  `protobuf:"varint,3,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_consumer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *HeartbeatRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *HeartbeatRequest) GetGenerationId() int32 {
	if x != nil {
		return x.GenerationId
	}
	return 0
}

type HeartbeatResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RebalanceInProgress bool                   `protobuf:"varint,1,opt,name=rebalance_in_progress,json=rebalanceInProgress,proto3" json:"rebalance_in_progress,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_consumer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetRebalanceInProgress() bool {
	if x != nil {
		return x.RebalanceInProgress
	}
	return false
}

type LeaveGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupRequest) Reset() {
	*x = LeaveGroupRequest{}
	mi := &file_proto_consumer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupRequest) ProtoMessage() {}

func (x *LeaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_consumer_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *LeaveGroupRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type LeaveGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupResponse) Reset() {
	*x = LeaveGroupResponse{}
	mi := &file_proto_consumer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupResponse) ProtoMessage() {}

func (x *LeaveGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consumer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupResponse.ProtoReflect.Descriptor instead.
func (*LeaveGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_consumer_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_consumer_proto protoreflect.FileDescriptor

const file_proto_consumer_proto_rawDesc = "" +
	"\n" +
	"\x14proto/consumer.proto\x12\bconsumer\"N\n" +
	"\x10JoinGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\"\x90\x01\n" +
	"\x11JoinGroupResponse\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rgeneration_id\x18\x02 \x01(\x05R\fgenerationId\x12\x1b\n" +
	"\tis_leader\x18\x03 \x01(\bR\bisLeader\x12\x18\n" +
	"\amembers\x18\x04 \x03(\tR\amembers\"\xa1\x02\n" +
	"\x10SyncGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rgeneration_id\x18\x03 \x01(\x05R\fgenerationId\x12M\n" +
	"\vassignments\x18\x04 \x03(\v2+.consumer.SyncGroupRequest.AssignmentsEntryR\vassignments\x1a]\n" +
	"\x10AssignmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.consumer.PartitionAssignmentR\x05value:\x028\x01\"5\n" +
	"\x13PartitionAssignment\x12\x1e\n" +
	"\n" +
	"partitions\x18\x01 \x03(\x05R\n" +
	"partitions\"R\n" +
	"\x11SyncGroupResponse\x12=\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1d.consumer.PartitionAssignmentR\n" +
	"assignment\"s\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12#\n" +
	"\rgeneration_id\x18\x03 \x01(\x05R\fgenerationId\"G\n" +
	"\x11HeartbeatResponse\x122\n" +
	"\x15rebalance_in_progress\x18\x01 \x01(\bR\x13rebalanceInProgress\"O\n" +
	"\x11LeaveGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\".\n" +
	"\x12LeaveGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb0\x02\n" +
	"\x13ConsumerCoordinator\x12D\n" +
	"\tJoinGroup\x12\x1a.consumer.JoinGroupRequest\x1a\x1b.consumer.JoinGroupResponse\x12D\n" +
	"\tSyncGroup\x12\x1a.consumer.SyncGroupRequest\x1a\x1b.consumer.SyncGroupResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.consumer.HeartbeatRequest\x1a\x1b.consumer.HeartbeatResponse\x12G\n" +
	"\n" +
	"LeaveGroup\x12\x1b.consumer.LeaveGroupRequest\x1a\x1c.consumer.LeaveGroupResponseB$Z\"github.com/sagar/streamforge/protob\x06proto3"

var (
	file_proto_consumer_proto_rawDescOnce sync.Once
	file_proto_consumer_proto_rawDescData []byte
)

func file_proto_consumer_proto_rawDescGZIP() []byte {
	file_proto_consumer_proto_rawDescOnce.Do(func() {
		file_proto_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consumer_proto_rawDesc), len(file_proto_consumer_proto_rawDesc)))
	})
	return file_proto_consumer_proto_rawDescData
}

var file_proto_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_consumer_proto_goTypes = []any{
	(*JoinGroupRequest)(nil),    // 0: consumer.JoinGroupRequest
	(*JoinGroupResponse)(nil),   // 1: consumer.JoinGroupResponse
	(*SyncGroupRequest)(nil),    // 2: consumer.SyncGroupRequest
	(*PartitionAssignment)(nil), // 3: consumer.PartitionAssignment
	(*SyncGroupResponse)(nil),   // 4: consumer.SyncGroupResponse
	(*HeartbeatRequest)(nil),    // 5: consumer.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 6: consumer.HeartbeatResponse
	(*LeaveGroupRequest)(nil),   // 7: consumer.LeaveGroupRequest
	(*LeaveGroupResponse)(nil),  // 8: consumer.LeaveGroupResponse
	nil,                         // 9: consumer.SyncGroupRequest.AssignmentsEntry
}
var file_proto_consumer_proto_depIdxs = []int32{
	9, // 0: consumer.SyncGroupRequest.assignments:type_name -> consumer.SyncGroupRequest.AssignmentsEntry
	3, // 1: consumer.SyncGroupResponse.assignment:type_name -> consumer.PartitionAssignment
	3, // 2: consumer.SyncGroupRequest.AssignmentsEntry.value:type_name -> consumer.PartitionAssignment
	0, // 3: consumer.ConsumerCoordinator.JoinGroup:input_type -> consumer.JoinGroupRequest
	2, // 4: consumer.ConsumerCoordinator.SyncGroup:input_type -> consumer.SyncGroupRequest
	5, // 5: consumer.ConsumerCoordinator.Heartbeat:input_type -> consumer.HeartbeatRequest
	7, // 6: consumer.ConsumerCoordinator.LeaveGroup:input_type -> consumer.LeaveGroupRequest
	1, // 7: consumer.ConsumerCoordinator.JoinGroup:output_type -> consumer.JoinGroupResponse
	4, // 8: consumer.ConsumerCoordinator.SyncGroup:output_type -> consumer.SyncGroupResponse
	6, // 9: consumer.ConsumerCoordinator.Heartbeat:output_type -> consumer.HeartbeatResponse
	8, // 10: consumer.ConsumerCoordinator.LeaveGroup:output_type -> consumer.LeaveGroupResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_consumer_proto_init() }
func file_proto_consumer_proto_init() {
	if File_proto_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consumer_proto_rawDesc), len(file_proto_consumer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consumer_proto_goTypes,
		DependencyIndexes: file_proto_consumer_proto_depIdxs,
		MessageInfos:      file_proto_consumer_proto_msgTypes,
	}.Build()
	File_proto_consumer_proto = out.File
	file_proto_consumer_proto_goTypes = nil
	file_proto_consumer_proto_depIdxs = nil
}
