// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/processor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckpointBarrier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId  int64                  `protobuf:"varint,1,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointBarrier) Reset() {
	*x = CheckpointBarrier{}
	mi := &file_proto_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointBarrier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointBarrier) ProtoMessage() {}

func (x *CheckpointBarrier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointBarrier.ProtoReflect.Descriptor instead.
func (*CheckpointBarrier) Descriptor() ([]byte, []int) {
	return file_proto_processor_proto_rawDescGZIP(), []int{0}
}

func (x *CheckpointBarrier) GetCheckpointId() int64 {
	if x != nil {
		return x.CheckpointId
	}
	return 0
}

func (x *CheckpointBarrier) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SpeculativeTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartitionId    int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	CheckpointId   int64                  `protobuf:"varint,2,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	TargetWindowId int64                  `protobuf:"varint,3,opt,name=target_window_id,json=targetWindowId,proto3" json:"target_window_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpeculativeTaskRequest) Reset() {
	*x = SpeculativeTaskRequest{}
	mi := &file_proto_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeculativeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeculativeTaskRequest) ProtoMessage() {}

func (x *SpeculativeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeculativeTaskRequest.ProtoReflect.Descriptor instead.
func (*SpeculativeTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_processor_proto_rawDescGZIP(), []int{1}
}

func (x *SpeculativeTaskRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *SpeculativeTaskRequest) GetCheckpointId() int64 {
	if x != nil {
		return x.CheckpointId
	}
	return 0
}

func (x *SpeculativeTaskRequest) GetTargetWindowId() int64 {
	if x != nil {
		return x.TargetWindowId
	}
	return 0
}

type ArbitratorSubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowId      int64                  `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	PartitionId   int32                  `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	ResultPayload []byte                 `protobuf:"bytes,3,opt,name=result_payload,json=resultPayload,proto3" json:"result_payload,omitempty"`
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // distinguishes original vs speculative
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbitratorSubmission) Reset() {
	*x = ArbitratorSubmission{}
	mi := &file_proto_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitratorSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitratorSubmission) ProtoMessage() {}

func (x *ArbitratorSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitratorSubmission.ProtoReflect.Descriptor instead.
func (*ArbitratorSubmission) Descriptor() ([]byte, []int) {
	return file_proto_processor_proto_rawDescGZIP(), []int{2}
}

func (x *ArbitratorSubmission) GetWindowId() int64 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

func (x *ArbitratorSubmission) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *ArbitratorSubmission) GetResultPayload() []byte {
	if x != nil {
		return x.ResultPayload
	}
	return nil
}

func (x *ArbitratorSubmission) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

var File_proto_processor_proto protoreflect.FileDescriptor

const file_proto_processor_proto_rawDesc = "" +
	"\n" +
	"\x15proto/processor.proto\x12\tprocessor\"V\n" +
	"\x11CheckpointBarrier\x12#\n" +
	"\rcheckpoint_id\x18\x01 \x01(\x03R\fcheckpointId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x8a\x01\n" +
	"\x16SpeculativeTaskRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12#\n" +
	"\rcheckpoint_id\x18\x02 \x01(\x03R\fcheckpointId\x12(\n" +
	"\x10target_window_id\x18\x03 \x01(\x03R\x0etargetWindowId\"\x9a\x01\n" +
	"\x14ArbitratorSubmission\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\x03R\bwindowId\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\x12%\n" +
	"\x0eresult_payload\x18\x03 \x01(\fR\rresultPayload\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerIdB$Z\"github.com/sagar/streamforge/protob\x06proto3"

var (
	file_proto_processor_proto_rawDescOnce sync.Once
	file_proto_processor_proto_rawDescData []byte
)

func file_proto_processor_proto_rawDescGZIP() []byte {
	file_proto_processor_proto_rawDescOnce.Do(func() {
		file_proto_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_processor_proto_rawDesc), len(file_proto_processor_proto_rawDesc)))
	})
	return file_proto_processor_proto_rawDescData
}

var file_proto_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_processor_proto_goTypes = []any{
	(*CheckpointBarrier)(nil),      // 0: processor.CheckpointBarrier
	(*SpeculativeTaskRequest)(nil), // 1: processor.SpeculativeTaskRequest
	(*ArbitratorSubmission)(nil),   // 2: processor.ArbitratorSubmission
}
var file_proto_processor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_processor_proto_init() }
func file_proto_processor_proto_init() {
	if File_proto_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_processor_proto_rawDesc), len(file_proto_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_processor_proto_goTypes,
		DependencyIndexes: file_proto_processor_proto_depIdxs,
		MessageInfos:      file_proto_processor_proto_msgTypes,
	}.Build()
	File_proto_processor_proto = out.File
	file_proto_processor_proto_goTypes = nil
	file_proto_processor_proto_depIdxs = nil
}
